Amirhossein Kargaran - Behnam Jafarboland - Arman Pourghorban

In [5]:
import numpy as np
def mgs(A):
    m,n = A.shape
    v = np.zeros((m,n))
    R = np.zeros((n,n))
    Q = np.zeros((m,n))

    for i in range(0,n):
        v[:,i] = A[:,i]
        
    for i in range(0,n):
        R[i,i] = np.linalg.norm(v[:,i],2)
        Q[:,i] = v[:,i]/R[i,i]
        for j in range(i,n):
            R[i,j] = np.dot(Q[:,i].T, v[:,j])
            v[:,j] = v[:,j] - R[i,j]*Q[:,i]

    return (Q,R)

if __name__ == '__main__':
    A = np.array([[ 12, -51,   4],
                  [  6, 167, -68],
                  [ -4,  24, -41]])
    Q, R = mgs(A)
    print("Q = " + str(Q))
    print("R = " + str(R))


Q = [[ 0.85714286 -0.39428571 -0.33142857]
 [ 0.42857143  0.90285714  0.03428571]
 [-0.28571429  0.17142857 -0.94285714]]
R = [[ 14.  21. -14.]
 [  0. 175. -70.]
 [  0.   0.  35.]]
